// <auto-generated />
using System;
using DungeonsAndExiles.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DungeonsAndExiles.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240530121216_AddStaminaForPlayer")]
    partial class AddStaminaForPlayer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackpackItem", b =>
                {
                    b.Property<Guid>("BackpackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("BackpackId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BackpackItem");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Backpack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Backpacks");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Defence")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ac64752-61d9-438e-ba1e-e2894b564ee9"),
                            Damage = 0,
                            Defence = 5,
                            Name = "Basic Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("af46502c-de0d-4a7b-ad6d-4fb2d6bc62cf"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Leather Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("9420a79e-6666-4028-95cf-1facbf19ab77"),
                            Damage = 0,
                            Defence = 15,
                            Name = "Iron Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("8741c040-de50-4220-a312-f715c4b57027"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Steel Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("a12f38ab-be4d-43a9-9e3f-71d2da615ae0"),
                            Damage = 0,
                            Defence = 25,
                            Name = "Titanium Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("2b23b799-6d83-4d46-bbc2-6d864dcd2df6"),
                            Damage = 0,
                            Defence = 5,
                            Name = "Basic Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("42c9c7e0-796c-4ee7-ba3f-4c0258f128b0"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Leather Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("572ec2e8-7917-48c5-8a90-57c704335f5a"),
                            Damage = 0,
                            Defence = 15,
                            Name = "Iron Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("5bf861bf-345b-4d88-a532-ed4dd4b4dc51"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Steel Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("5ad29be6-96b8-49d9-b842-c13e1162a71f"),
                            Damage = 0,
                            Defence = 25,
                            Name = "Titanium Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("448c8cd0-040d-43a4-9ee0-cd916ccd6a77"),
                            Damage = 10,
                            Defence = 0,
                            Name = "Basic Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("0d6ebed0-22a8-4c9c-84d2-3a554a78b830"),
                            Damage = 15,
                            Defence = 0,
                            Name = "Iron Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("2cda8a7f-0640-4a5c-8cb5-3a3d60164d99"),
                            Damage = 20,
                            Defence = 0,
                            Name = "Steel Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("582eb83f-90ec-4d71-8c2c-b695b88aee41"),
                            Damage = 25,
                            Defence = 0,
                            Name = "Titanium Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("689f511b-4f71-4158-8328-0393c8bab9af"),
                            Damage = 30,
                            Defence = 0,
                            Name = "Diamond Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("60f64182-6af4-4eae-aff0-075694aba774"),
                            Damage = 0,
                            Defence = 5,
                            Name = "Basic Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("288639ab-2fb9-42aa-8813-848410413986"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Leather Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("6940a620-9a00-4e04-b786-026d9bff8542"),
                            Damage = 0,
                            Defence = 15,
                            Name = "Iron Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("c89e3f38-9971-480a-9aaa-1368de12ef4d"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Steel Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("53a39154-acfc-4e73-b176-9339de936d6e"),
                            Damage = 0,
                            Defence = 25,
                            Name = "Titanium Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("62be2166-ca43-4b07-a721-89e5ca46644f"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Basic Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("ed3671d5-fa16-4e98-be57-f86216748768"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Leather Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("0ad01736-adcc-4636-ae49-9edf92e6d3c7"),
                            Damage = 0,
                            Defence = 30,
                            Name = "Iron Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("f35dd188-a76c-46da-9578-ce4948d3785e"),
                            Damage = 0,
                            Defence = 40,
                            Name = "Steel Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("3b00c739-5af0-44a3-b490-430347ddf37a"),
                            Damage = 0,
                            Defence = 50,
                            Name = "Titanium Armor",
                            Type = "Body Armor"
                        });
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Defence")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8122d8d9-7f3d-486b-85bb-4d4405f29fbe"),
                            Damage = 5,
                            Defence = 1,
                            Health = 30,
                            Level = 1,
                            Name = "Witch"
                        },
                        new
                        {
                            Id = new Guid("7933e43c-dafa-44c8-8e39-ffcd93c2afee"),
                            Damage = 10,
                            Defence = 5,
                            Health = 50,
                            Level = 5,
                            Name = "Deadeye"
                        },
                        new
                        {
                            Id = new Guid("e8c5f7f4-bf55-47ff-927b-8862f23bfbc9"),
                            Damage = 20,
                            Defence = 10,
                            Health = 70,
                            Level = 10,
                            Name = "Assassin"
                        },
                        new
                        {
                            Id = new Guid("18b87d72-d7fa-461a-a0a0-7458de86ca74"),
                            Damage = 30,
                            Defence = 15,
                            Health = 75,
                            Level = 15,
                            Name = "Occultist"
                        },
                        new
                        {
                            Id = new Guid("532b1c5e-6d99-474f-82e3-253d49e8ad91"),
                            Damage = 40,
                            Defence = 30,
                            Health = 150,
                            Level = 20,
                            Name = "Elementalist"
                        },
                        new
                        {
                            Id = new Guid("3261b5dc-615f-4e5f-a7d9-a758a5cb08bb"),
                            Damage = 100,
                            Defence = 50,
                            Health = 300,
                            Level = 25,
                            Name = "Juggernaut"
                        });
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackpackId")
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Defence")
                        .HasColumnType("integer");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca640947-7f3c-42f1-9c58-f9910dd1548a"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("0f33e895-d123-482a-aaab-57317e7f4a26"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d505a84-bdf2-4aea-97a1-5a1caf2fe18b"),
                            Email = "admin@admin.com",
                            Name = "Admin",
                            Password = "$2a$10$MCqolAF0BeDsVXsCdTnsJu2jU/UYjDdzpAP10nEOl/VniPL.pb1DS",
                            RefreshTokenExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("ca640947-7f3c-42f1-9c58-f9910dd1548a")
                        },
                        new
                        {
                            Id = new Guid("55117ef5-2cef-439b-9f4e-2ba8bdb0ac6f"),
                            Email = "john@doe.com",
                            Name = "John",
                            Password = "$2a$10$4gIj0xdc6E7V2jhmINOqsODUCYzxyuRbPI0ZCLnObzLEhk3A0kU1u",
                            RefreshTokenExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("0f33e895-d123-482a-aaab-57317e7f4a26")
                        },
                        new
                        {
                            Id = new Guid("d46b568d-f865-4f99-b6a4-06ba30f78d65"),
                            Email = "chris@wilson.com",
                            Name = "Chris",
                            Password = "$2a$10$ecIPRZch2DcswoRiL1hesu1dnPqtRHdGuXbiRd2H9XT.NtujUmtFW",
                            RefreshTokenExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("0f33e895-d123-482a-aaab-57317e7f4a26")
                        });
                });

            modelBuilder.Entity("EquipmentItem", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("EquipmentId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("EquipmentItem");
                });

            modelBuilder.Entity("BackpackItem", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Backpack", null)
                        .WithMany()
                        .HasForeignKey("BackpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Backpack", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Player", "Player")
                        .WithOne("Backpack")
                        .HasForeignKey("DungeonsAndExiles.Api.Models.Domain.Backpack", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Equipment", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Player", "Player")
                        .WithOne("Equipment")
                        .HasForeignKey("DungeonsAndExiles.Api.Models.Domain.Equipment", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Player", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.User", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EquipmentItem", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Player", b =>
                {
                    b.Navigation("Backpack")
                        .IsRequired();

                    b.Navigation("Equipment")
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.User", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
