// <auto-generated />
using System;
using DungeonsAndExiles.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DungeonsAndExiles.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240529092109_AddRefreshToken")]
    partial class AddRefreshToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackpackItem", b =>
                {
                    b.Property<Guid>("BackpackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("BackpackId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BackpackItem");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Backpack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Backpacks");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Defence")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f09a7a96-44a4-47c6-8b02-35bbc29fc1ad"),
                            Damage = 0,
                            Defence = 5,
                            Name = "Basic Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("01bfec6b-3690-4910-9ce9-fa8abd58017b"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Leather Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("b3613013-6b20-48e5-b860-8baead982749"),
                            Damage = 0,
                            Defence = 15,
                            Name = "Iron Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("83a4b006-4f70-45ec-8747-fd6f23ebb905"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Steel Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("4cce7c47-2453-41c9-a5ae-44acefa16348"),
                            Damage = 0,
                            Defence = 25,
                            Name = "Titanium Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("8b5b625b-1fa4-4bf0-9ef5-98b292bf9339"),
                            Damage = 0,
                            Defence = 5,
                            Name = "Basic Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("a73a3735-303c-4bef-835e-dc94abe6d921"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Leather Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("fa2595d5-818e-4162-88db-38785a35d767"),
                            Damage = 0,
                            Defence = 15,
                            Name = "Iron Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("3578569a-4f83-4e84-8310-7b0209bc9ab4"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Steel Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("2f6d74a2-a309-4189-a838-180ff9c7ed7a"),
                            Damage = 0,
                            Defence = 25,
                            Name = "Titanium Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("147c03ee-f078-4b90-8523-13bea1cb2aca"),
                            Damage = 10,
                            Defence = 0,
                            Name = "Basic Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("ff518512-7619-431c-8ad7-196bebbc93a2"),
                            Damage = 15,
                            Defence = 0,
                            Name = "Iron Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("96dca947-5a8f-4a1e-9771-e76e3d692dc4"),
                            Damage = 20,
                            Defence = 0,
                            Name = "Steel Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("47f96b23-df9c-468f-93bb-c2c09c6d8771"),
                            Damage = 25,
                            Defence = 0,
                            Name = "Titanium Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("cab56cfd-0d16-4117-a5b8-b76bb81fa45e"),
                            Damage = 30,
                            Defence = 0,
                            Name = "Diamond Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("fe4b4f27-b124-4c2d-9699-cbeee458902b"),
                            Damage = 0,
                            Defence = 5,
                            Name = "Basic Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("44a1f559-1141-4d83-b0cc-a75dc08129d8"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Leather Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("f91eb875-281f-46fe-8610-4bd90a113c0d"),
                            Damage = 0,
                            Defence = 15,
                            Name = "Iron Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("c8325ef8-9eef-4cce-915d-fea5b3d75bce"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Steel Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("389b91c6-2455-4ba5-811f-6d7baf3a1dde"),
                            Damage = 0,
                            Defence = 25,
                            Name = "Titanium Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("2225a7ab-b612-45c8-a412-f72a62985921"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Basic Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("88657229-5149-4a69-922d-0120ae485443"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Leather Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("b6453488-a6d6-4023-9214-a535de404462"),
                            Damage = 0,
                            Defence = 30,
                            Name = "Iron Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("84ec96f7-c52f-4d8c-9d23-3b11f3f0f455"),
                            Damage = 0,
                            Defence = 40,
                            Name = "Steel Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("e7cf9a88-8558-45b0-a4af-5eb997fad69e"),
                            Damage = 0,
                            Defence = 50,
                            Name = "Titanium Armor",
                            Type = "Body Armor"
                        });
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Defence")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34399507-0167-4988-b9c1-a0f3c1bbb262"),
                            Damage = 5,
                            Defence = 1,
                            Health = 30,
                            Level = 1,
                            Name = "Witch"
                        },
                        new
                        {
                            Id = new Guid("2df9dd43-0597-49f7-a5d8-5a0625dbdc0f"),
                            Damage = 10,
                            Defence = 5,
                            Health = 50,
                            Level = 5,
                            Name = "Deadeye"
                        },
                        new
                        {
                            Id = new Guid("2950121c-4c23-444e-8d50-3a27604ec120"),
                            Damage = 20,
                            Defence = 10,
                            Health = 70,
                            Level = 10,
                            Name = "Assassin"
                        },
                        new
                        {
                            Id = new Guid("ee39bda6-9056-4151-865f-5eeccfaf34ec"),
                            Damage = 30,
                            Defence = 15,
                            Health = 75,
                            Level = 15,
                            Name = "Occultist"
                        },
                        new
                        {
                            Id = new Guid("e808e923-75d7-4513-8349-4d0643ed1fb1"),
                            Damage = 40,
                            Defence = 30,
                            Health = 150,
                            Level = 20,
                            Name = "Elementalist"
                        },
                        new
                        {
                            Id = new Guid("f4f80fb0-ac71-4e8e-974f-da6562d31491"),
                            Damage = 100,
                            Defence = 50,
                            Health = 300,
                            Level = 25,
                            Name = "Juggernaut"
                        });
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackpackId")
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Defence")
                        .HasColumnType("integer");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d86976c1-c91e-454a-95a0-f28c6e9ce50a"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("ca494e53-13d7-4eb0-a3e6-08c341ee9a59"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68db6b58-f11c-4412-ab08-dfb11e822900"),
                            Email = "admin@admin.com",
                            Name = "Admin",
                            Password = "$2a$10$UFZ74rM4Tw4Pn5nXj7QaHOTEhfMWrmckFTjoKa775E4LpKEuMCBB6",
                            RefreshTokenExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("d86976c1-c91e-454a-95a0-f28c6e9ce50a")
                        },
                        new
                        {
                            Id = new Guid("491efe03-17a4-40b4-bb99-21c879d7b5e4"),
                            Email = "john@doe.com",
                            Name = "John",
                            Password = "$2a$10$05y.Cf9DQ9H2sXhew1q72..3r.rkzJZEhhw8h1Ho/P/vVjoqqNCI6",
                            RefreshTokenExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("ca494e53-13d7-4eb0-a3e6-08c341ee9a59")
                        },
                        new
                        {
                            Id = new Guid("08e98811-4841-4877-923e-d210defb473b"),
                            Email = "chris@wilson.com",
                            Name = "Chris",
                            Password = "$2a$10$N0SQfcoztF24QMDMjL/jbux.5z20qHtr2clwDPKx4GzrK9vFyBLKu",
                            RefreshTokenExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("ca494e53-13d7-4eb0-a3e6-08c341ee9a59")
                        });
                });

            modelBuilder.Entity("EquipmentItem", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("EquipmentId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("EquipmentItem");
                });

            modelBuilder.Entity("BackpackItem", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Backpack", null)
                        .WithMany()
                        .HasForeignKey("BackpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Backpack", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Player", "Player")
                        .WithOne("Backpack")
                        .HasForeignKey("DungeonsAndExiles.Api.Models.Domain.Backpack", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Equipment", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Player", "Player")
                        .WithOne("Equipment")
                        .HasForeignKey("DungeonsAndExiles.Api.Models.Domain.Equipment", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Player", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.User", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EquipmentItem", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Player", b =>
                {
                    b.Navigation("Backpack")
                        .IsRequired();

                    b.Navigation("Equipment")
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.User", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
