// <auto-generated />
using System;
using DungeonsAndExiles.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DungeonsAndExiles.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240525085136_Add_Monster_and_items_data")]
    partial class Add_Monster_and_items_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackpackItem", b =>
                {
                    b.Property<Guid>("BackpackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("BackpackId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BackpackItem");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Backpack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Backpacks");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Defence")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1de89f7-ac55-45e7-bcf9-fe969f9a4ec3"),
                            Damage = 0,
                            Defence = 5,
                            Name = "Basic Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("7f6c270c-a2d8-4d94-b66e-a1d10cf910f1"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Leather Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("14d02621-e7c6-4533-b071-42283e532607"),
                            Damage = 0,
                            Defence = 15,
                            Name = "Iron Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("b994235a-a9aa-4171-8921-a93a6d5ddd2f"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Steel Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("a8b7ae30-9169-41c1-9c80-73a691fcda58"),
                            Damage = 0,
                            Defence = 25,
                            Name = "Titanium Gloves",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = new Guid("4099f361-3bd0-473e-b6e4-f2021d67b26c"),
                            Damage = 0,
                            Defence = 5,
                            Name = "Basic Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("2fccc62f-7c29-4fa1-ab67-8e60c110b966"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Leather Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("bb70a4c9-489b-4940-967e-76ea3b8a9c2d"),
                            Damage = 0,
                            Defence = 15,
                            Name = "Iron Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("c59c3109-6dd2-450c-acfe-deb2d1e54686"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Steel Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("8e466a6f-110e-4973-8365-12833a838200"),
                            Damage = 0,
                            Defence = 25,
                            Name = "Titanium Boots",
                            Type = "Boots"
                        },
                        new
                        {
                            Id = new Guid("1e8af1ca-e2c6-4476-bd53-40230e0d0688"),
                            Damage = 10,
                            Defence = 0,
                            Name = "Basic Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("abd59e31-25e4-4f03-939e-e20367efd2ed"),
                            Damage = 15,
                            Defence = 0,
                            Name = "Iron Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("a039b7f7-2fab-4368-9faf-51094430f514"),
                            Damage = 20,
                            Defence = 0,
                            Name = "Steel Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("3c9d0328-0b87-46e8-9dba-69d4094daf83"),
                            Damage = 25,
                            Defence = 0,
                            Name = "Titanium Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("9525f977-2877-4843-86d3-70422d00fcf0"),
                            Damage = 30,
                            Defence = 0,
                            Name = "Diamond Sword",
                            Type = "Weapon"
                        },
                        new
                        {
                            Id = new Guid("48728490-cc31-44b4-8cc8-36bb3ad8cb68"),
                            Damage = 0,
                            Defence = 5,
                            Name = "Basic Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("f4909d80-f3a1-4d65-88ad-d5de952df265"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Leather Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("2f64247e-7355-4177-ad9c-7e2d209cf59e"),
                            Damage = 0,
                            Defence = 15,
                            Name = "Iron Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("5a2d11af-ff9b-4967-8210-5a44de70dfe8"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Steel Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("dd44a08d-ee0d-4551-997c-9f68c9a20de4"),
                            Damage = 0,
                            Defence = 25,
                            Name = "Titanium Helmet",
                            Type = "Helmet"
                        },
                        new
                        {
                            Id = new Guid("572d4b5f-f0a5-4841-a2db-9b308b774332"),
                            Damage = 0,
                            Defence = 10,
                            Name = "Basic Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("0f7fdf98-f115-46e0-a188-3bf93e13f4d5"),
                            Damage = 0,
                            Defence = 20,
                            Name = "Leather Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("107b0094-b5a2-4749-a2a1-9dc304ee9a40"),
                            Damage = 0,
                            Defence = 30,
                            Name = "Iron Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("86f3ea29-6b49-4c7f-8fcc-4906b43b0d37"),
                            Damage = 0,
                            Defence = 40,
                            Name = "Steel Armor",
                            Type = "Body Armor"
                        },
                        new
                        {
                            Id = new Guid("623a92fd-2d05-487c-9d8a-ddbc89e053c4"),
                            Damage = 0,
                            Defence = 50,
                            Name = "Titanium Armor",
                            Type = "Body Armor"
                        });
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Defence")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69ec19bc-9dea-47f1-b795-fc1eca9859f3"),
                            Damage = 5,
                            Defence = 1,
                            Health = 30,
                            Level = 1,
                            Name = "Witch"
                        },
                        new
                        {
                            Id = new Guid("27cf3148-f88a-4bb2-9eb8-a8619c0f605d"),
                            Damage = 10,
                            Defence = 5,
                            Health = 50,
                            Level = 5,
                            Name = "Deadeye"
                        },
                        new
                        {
                            Id = new Guid("b7aa4f42-5d07-49a6-9765-f29c1731ff7c"),
                            Damage = 20,
                            Defence = 10,
                            Health = 70,
                            Level = 10,
                            Name = "Assassin"
                        },
                        new
                        {
                            Id = new Guid("20e2d81b-69ed-460e-b7ef-59fb5f83c8e0"),
                            Damage = 30,
                            Defence = 15,
                            Health = 75,
                            Level = 15,
                            Name = "Occultist"
                        },
                        new
                        {
                            Id = new Guid("8a88dc07-c4d1-4961-823d-01be4c41ea1e"),
                            Damage = 40,
                            Defence = 30,
                            Health = 150,
                            Level = 20,
                            Name = "Elementalist"
                        },
                        new
                        {
                            Id = new Guid("0f1ae3e4-bd52-4506-b907-6d25120742ef"),
                            Damage = 100,
                            Defence = 50,
                            Health = 300,
                            Level = 25,
                            Name = "Juggernaut"
                        });
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackpackId")
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Defence")
                        .HasColumnType("integer");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b357bb36-eeb2-4744-b1a8-4d65faa728ee"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("2d07e175-36bc-4c0f-af96-aae5e46053e9"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("649a6c45-8cd2-4442-b65d-80e72bb9c1a2"),
                            Email = "admin@admin.com",
                            Name = "Admin",
                            Password = "$2a$10$JGiFivsE2xIHTHkFECH3fux6ZRXikmepbUSr2.y6L8KDwoNVHyGDW",
                            RoleId = new Guid("b357bb36-eeb2-4744-b1a8-4d65faa728ee")
                        },
                        new
                        {
                            Id = new Guid("07a6368c-57cb-4d02-b313-8839d58804ba"),
                            Email = "john@doe.com",
                            Name = "John",
                            Password = "$2a$10$XrOGCpg5LSOHgAmmzCYFwuBJwyY93.cgiHog9GijfQScdSpmGo7DO",
                            RoleId = new Guid("2d07e175-36bc-4c0f-af96-aae5e46053e9")
                        },
                        new
                        {
                            Id = new Guid("f1b0f441-e05e-4096-88cb-aab441cb7030"),
                            Email = "chris@wilson.com",
                            Name = "Chris",
                            Password = "$2a$10$0cCd8qZP7VkLnPfNg9DG4uW4UvKVXMsdN7n4/BCkGgGojxjbOlcQa",
                            RoleId = new Guid("2d07e175-36bc-4c0f-af96-aae5e46053e9")
                        });
                });

            modelBuilder.Entity("EquipmentItem", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("EquipmentId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("EquipmentItem");
                });

            modelBuilder.Entity("BackpackItem", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Backpack", null)
                        .WithMany()
                        .HasForeignKey("BackpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Backpack", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Player", "Player")
                        .WithOne("Backpack")
                        .HasForeignKey("DungeonsAndExiles.Api.Models.Domain.Backpack", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Equipment", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Player", "Player")
                        .WithOne("Equipment")
                        .HasForeignKey("DungeonsAndExiles.Api.Models.Domain.Equipment", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Player", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.User", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EquipmentItem", b =>
                {
                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DungeonsAndExiles.Api.Models.Domain.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.Player", b =>
                {
                    b.Navigation("Backpack")
                        .IsRequired();

                    b.Navigation("Equipment")
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonsAndExiles.Api.Models.Domain.User", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
